### ISSUE TITLE
C-CDA to FHIR

### ISSUE THREAD

**Issue by wahmedswl** [lantanagroup/stylesheets#11]
Hi, C-CDA to FHIR and FHIR to C-CDA mapping is supported? I asked this on https://github.com/ewoutkramer/fhir-net-api/issues/315.

Any help would be appreciated.

Thanks

**Comment by EricParapini-Lantanagroup** [comment]
Hi @wahmedswl, 

I reached out to @rgeimer about this. Let me know if you were contacted.

**Comment by rgeimer** [comment]
This stylesheet is for rendering CDA documents (i.e. CDA to HTML), and does not support CDA

________________________________

**Comment by rgeimer** [comment]
This stylesheet is for rendering CDA documents (i.e. CDA to HTML), and does not support CDA to FHIR conversion. However, we will be releasing a separate transform for CDA -> FHIR conversion for Pharmacist Care Plan document types, and this will be open source and extensible to other CDA document types in the future.

________________________________

**Comment by wahmedswl** [comment]
@rgeimer thanks
