### ISSUE TITLE
how to use this project

### ISSUE THREAD

**Issue by mshen6666** [lantanagroup/stylesheets#13]
I now have a cda document xml, if you want to use this tool to generate a html, how should I operate, after reading the readme did not understand the use of the way, can answer a little, thank you very much!

**Comment by seanmcilvenna** [comment]
Hi @mshen6666 ,
Did you see the [Use](https://github.com/lantanagroup/stylesheets#use) section on the main README?
You can either attach the stylesheet using `<?xml-stylesheet type="text/xsl" href="./cda.xsl"?>` to the top of the XML, or you can use a tool such as OxygenXML or you can download Saxon and transform your XML using Java like so: `java -jar saxon9he.jar -o:outputfile.xml data.xml transform.xslt`
